HotelManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RoomManagement.urls')),
]+staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RoomManagement/urls.py
from django.urls import path
from .views import *


app_name = 'room_management'

urlpatterns = [

    path('', landing_page, name='landing-page'),
    path('home/', home, name='home'),
    path('customer/', add_customer, name='add-customer'),
    path('login/', room_manager_login, name='login'),
    path('logout/', room_manager_logout, name='logout'),

    path('customers/', customers_list, name='customers-list'),
    path('customers/<customer_aadhaar>/', customer_profile, name='customer-profile'),
    path('customers/<customer_aadhaar>/edit_customer/', edit_customer_details, name='edit-details'),
    path('customers/<customer_aadhaar>/delete_customer/', delete_customer, name='delete-customer'),

    path('book_room/', book_room, name='book-room'),
    path('booked_rooms',booked_room, name='booked_rooms'),

]

RoomService/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'rooms_service'

urlpatterns = [

]

customers/models.py
from django.db import models
from django.contrib.auth.models import User


# Address...
class Address(models.Model):
    country = models.CharField(max_length=20, blank=False)
    state = models.CharField(max_length=30, blank=False)
    city = models.CharField(max_length=30, blank=False)
    house_number = models.CharField(max_length=20, blank=False)

    def __str__(self):
        return self.country + ', ' + self.city


# Contact_Details...
class ContactDetails(models.Model):
    phone_number = models.BigIntegerField()
    email = models.EmailField()

    def __str__(self):
        return self.email + ', ' + str(self.phone_number)


# Customers Database...
class Customers(models.Model):

    # Customer Personals...
    customer_name = models.CharField(max_length=200, null=False, unique=True)
    customer_dob = models.DateField()
    customer_aadhaar = models.PositiveIntegerField(blank=False, unique=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    contact_details = models.OneToOneField(ContactDetails, on_delete=models.CASCADE)
    customer_image = models.ImageField(upload_to='Profile Images/', null=True)
    gender = models.CharField(max_length=10)

    def __str__(self):
        return self.customer_name

templates/customers/customers.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'customers_list/css/styles.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Customers</title>
</head>
<body style="background-color: #232525">

<div class="container-fluid" style="padding-top: 120px">
    <div class="row">
        <div class="col-lg-12">
            <nav class="colorlib-nav">
                <div class="top-menu">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-2 text-center">
                                <div id="colorlib-logo">
                                    <a href="{% url 'room_management:home' %}" style="text-decoration: none">BOOK HOTEL</a>
                                </div>
                            </div>
                            <div class="col-md-10 text-right">
                                <ul>
                                    <li class="active">
                                        <a href="{% url 'room_management:home' %}" style="text-decoration: none">Home</a>
                                    </li>
                                    <li class="btn-cta">
                                        <a href="{% url 'room_management:logout' %}" style="text-decoration: none">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <div class="row">
        {% for customer in customers %}
            <div class="col-lg-3">
                <form method="POST" action="{% url 'room_management:customer-profile' customer.customer_aadhaar %}">
                    {% csrf_token %}
                    <div class="card" style="width: 100%;">
                        <div style="background-color: rgba(0, 0, 0, 0.2)">
                            {% if customer.customer_image.url != None %}
                                <img class="card-img-top" src="{{ MEDIA_URL }}{{ customer.customer_image.url }}" alt="Card image cap">
                            {% else %}
                                <h3>No Image</h3>
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">{{ customer.customer_name }}</h4>
                        </div>

                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><b>Aadhaar:</b> {{ customer.customer_aadhaar }}</li>
                            <li class="list-group-item"><b>Email:</b> {{ customer.contact_details.email }}</li>
                        </ul>
                        <div class="card-body" style="text-align: center">
                            <button class="card-link btn btn-success">Show all details</button>
                        </div>
                    </div>
                </form>
            </div>
        {% endfor %}
    </div>
</div>

</body>
</html>