HotelManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RoomManagement.urls')),
]+staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RoomManagement/urls.py
from django.urls import path
from .views import *


app_name = 'room_management'

urlpatterns = [

    path('', landing_page, name='landing-page'),
    path('home/', home, name='home'),
    path('customer/', add_customer, name='add-customer'),
    path('login/', room_manager_login, name='login'),
    path('logout/', room_manager_logout, name='logout'),

    path('customers/', customers_list, name='customers-list'),
    path('customers/<customer_aadhaar>/', customer_profile, name='customer-profile'),
    path('customers/<customer_aadhaar>/edit_customer/', edit_customer_details, name='edit-details'),
    path('customers/<customer_aadhaar>/delete_customer/', delete_customer, name='delete-customer'),

    path('book_room/', book_room, name='book-room'),
    path('booked_rooms',booked_room, name='booked_rooms'),

]

RoomService/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'rooms_service'

urlpatterns = [

]

RoomManagement/models.py
from django.db import models
from django.contrib.auth.models import User


# Room Management Employees...
class RoomsManagingEmployees(models.Model):
    employee_user = models.OneToOneField(User, on_delete=models.CASCADE)
    employee_id = models.CharField(max_length=10)
    employee_dob = models.DateField()

    def __str__(self):
        return self.employee_id + ',' + self.employee_user.username

RoomManagement/views.py
import datetime
from datetime import timedelta
from django.http import HttpResponse
from django.shortcuts import render, redirect
from RoomService.models import *
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth import authenticate, login, logout
from customers.models import *
from django.contrib import messages
import threading
import time

# Counting total number of Customers...
number_of_customers = len(Customers.objects.all())
# .....................................

# Counting total number of Employees...
number_of_employees = len(RoomsManagingEmployees.objects.all())
# .....................................

# Counting total number of blocks...
number_of_blocks = 0
blocks = []

for block in BlockFloor.objects.values_list('block'):
    if block not in blocks:
        blocks.append(block)
        number_of_blocks += 1
    else:
        pass
# .....................................

# Counting total number of rooms...
number_of_rooms = len(Room.objects.all())

# .....................................

# Counting total types of rooms...
room_type_price = []
for room_type in RoomType.objects.all():
    room_type_price.append((room_type.type, room_type.room_price))


# .....................................
args = {'customers_count': number_of_customers, 'blocks_count': number_of_blocks, 'rooms_count': number_of_rooms,
        'employees_count': number_of_employees, 'room_type_price': room_type_price}


# Landing Page...

def landing_page(request):
    return render(request, 'room_management/landing_page.html', args)


def home(request):
    username = request.user.username
    args['username'] = username
    return render(request, 'room_management/home.html', args)


# Manager Registration...
def add_customer(request):
    if request.method == 'POST':
        # Customer Details...
        cust_aadhaar = request.POST['aadhaar']
        if not Customers.objects.filter(customer_aadhaar=cust_aadhaar):
            cust_name = request.POST['cust_name']
            cust_dob = request.POST['cust_dob']
            cust_gender = request.POST['gender']

            # Address...
            cust_country = request.POST['country']
            cust_city = request.POST['city']
            cust_state = request.POST['state']
            cust_house_number = request.POST['house_number']

            addr = Address.objects.create(country=cust_country, state=cust_state, city=cust_city, house_number=cust_house_number)
            addr.save()

            # ........................................

            # Contact Details...
            cust_email = request.POST['email']
            cust_phone_number = request.POST['phn_number']

            cntct = ContactDetails.objects.create(email=cust_email, phone_number=cust_phone_number)
            cntct.save()

            # ........................................

            try:
                cust_image = request.FILES['image']
            except:
                cust_image = None

            customer_details = Customers.objects.create(customer_aadhaar=cust_aadhaar, customer_name=cust_name,
                                                        customer_dob=cust_dob, address=addr, contact_details=cntct,
                                                        gender=cust_gender, customer_image=cust_image)
            customer_details.save()

            messages.success(request, 'Customer added successfully.')

            return redirect('room_management:home')

        else:
            messages.error(request, 'Customer Already Exists!!')

        return redirect('room_management:add-customer')

    else:
        return render(request, 'room_management/add_customer.html')


def edit_customer_details(request, customer_aadhaar):

    if request.method == 'POST':
        customer = Customers.objects.get(customer_aadhaar=customer_aadhaar)

        customer.customer_name = request.POST['cust_name']
        try:
            customer.customer_image = request.FILES['image']
        except:
            pass

        contact_details = ContactDetails.objects.get(phone_number=customer.contact_details.phone_number,
                                                     email=customer.contact_details.email)
        contact_details.phone_number = request.POST['phn_number']
        contact_details.email = request.POST['email']
        contact_details.save()

        customer.contact_details = contact_details

        customer.save()

    else:
        pass

    return redirect('room_management:customer-profile', customer_aadhaar)


def delete_customer(request, customer_aadhaar):
    customer = Customers.objects.get(customer_aadhaar=customer_aadhaar)
    address = Address.objects.get(country=customer.address.country, city=customer.address.city,
                                  state=customer.address.state, house_number=customer.address.house_number)
    contact_details = ContactDetails.objects.get(email=customer.contact_details.email,
                                                 phone_number=customer.contact_details.phone_number)

    customer.delete()
    address.delete()
    contact_details.delete()

    return redirect('room_management:customers-list')


# Room Management Login...
def room_manager_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)

            return redirect('room_management:home')

        else:
            messages.error(request, 'Invalid Login details')

        return redirect('room_management:login')

    else:
        return render(request, 'room_management/login.html')


# Logout...
def room_manager_logout(request):
    logout(request)
    return redirect('room_management:landing-page')


# Customers.............................................................................................................
def customers_list(request):
    customers = Customers.objects.all()
    customers = {'customers': customers}

    return render(request, 'customers/customers.html', customers)


def customer_profile(request, customer_aadhaar):
    customer_details = Customers.objects.get(customer_aadhaar=customer_aadhaar)
    customer = {'customer_details': customer_details}

    return render(request, 'room_management/profile.html', customer)


threads = []
# Booking A Room...
def book_room(request):

    request.session.set_expiry(240)
    empty_rooms = []
    for room in Room.objects.all():
        if room.booked_customer == None:
            empty_rooms.append(room)

    room_args = {'empty_rooms': empty_rooms, 'customers': Customers.objects.all()}

    if request.method == 'POST':
        selected_room = request.POST['room']

        selected_room = tuple(selected_room.split(','))

        floor = Floor.objects.get(floor=selected_room[1])
        block_floor = BlockFloor.objects.get(floor=floor, block=selected_room[0])
        room = Room.objects.get(block_floor=block_floor, room_number=selected_room[2])

        customer = Customers.objects.get(customer_aadhaar=request.POST['aadhaar'])
        booked_days = request.POST['days']

        deadline = datetime.datetime.now() + timedelta(days=int(booked_days))

        room.booked_customer = customer
        room.booked_time = datetime.datetime.now()
        room.booked_days = booked_days
        room.deadline = deadline

        room.save()

        thread = threading.Thread(target=unbook_room, args=(room,))
        thread.start()
        threads.append((thread, room))

        return redirect('room_management:home')

    return render(request, 'room_management/book_room.html', room_args)


def unbook_room(curr_room):
    time.sleep(int(curr_room.booked_days)*24*60*60)
    curr_room.booked_customer = None
    curr_room.booked_time = None
    curr_room.booked_days = None

    curr_room.save()
    for thread, room in threads:
        if room == curr_room:
            thread.join()
            break

    return redirect('room_management:booked_rooms')

def booked_room(request):
    booked_rooms = []
    for room in Room.objects.all():
        if room.booked_customer != None:
            booked_rooms.append(room)

    return render(request, 'room_management/booked_rooms.html',{'rooms':booked_rooms})

templates/room_management/add_customer.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

    <title>Sign Up Form by Colorlib</title>

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'add_customer/css/style.css' %}">
</head>
<body>

<nav class="colorlib-nav">
    <div class="top-menu">
        <div class="col-md-2 text-center">
            <div id="colorlib-logo"><a href="{% url 'room_management:landing-page' %}">BOOK HOTEL</a></div>
        </div>
        <div class="col-md-10 text-right">
            <ul>
                <li class="active"><a href="{% url 'room_management:landing-page' %}">Home</a></li>
                <li class="btn-cta"><a href="{% url 'room_management:logout' %}">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <form method="POST" class="register-form" id="register-form" enctype="multipart/form-data"
              action="{% url 'room_management:add-customer' %}">
            {% csrf_token %}
            <div class="col-lg-6 profile-img">
                <input type="file" accept=".png, .jpg, .jpeg" id="imageUpload" name="image" onchange="loadFile(event)">
                <label for="imageUpload">
                    <img src="{% static 'add_customer/images/add-image.png' %}" alt="" style="height: 500px" id="uploadImage"
                         title="Upload Profile Image">
                </label>
            </div>

            <div class="col-lg-6" id="details">
                <h3>CUSTOMER DETAILS:</h3>
                <div class="form-row">
                    <div class="form-group">
                        <label for="name">Full Name :</label>
                        <input type="text" name="cust_name" id="name" required/>
                    </div>
                    <div class="form-group">
                        <label for="aadhaar">Aadhaar No :</label>
                        <input type="number" name="aadhaar" id="aadhaar" required>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="birth_date">DOB :</label>
                        <input type="date" name="cust_dob" pattern="[0-9]{4}-[0-9]{1-2}-[0-9]{1-2}" id="birth_date"
                               placeholder="YYYY-MM-DD" required>
                    </div>
                    <div class="form-group">
                        <label for="gender">Gender: </label>
                        <select name="gender" id="gender" required>
                            <option>Male</option>
                            <option>Female</option>
                            <option>Other</option>
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="city">City :</label>
                        <input type="text" name="city" id="city" required/>
                    </div>
                    <div class="form-group">
                        <label for="house_no">House No:</label>
                        <input type="text" name="house_number" id="house_number" required/>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="state">State :</label>
                        <input type="text" name="state" id="state" required/>
                    </div>
                    <div class="form-group">
                        <label for="country">Country:</label>
                        <input type="text" name="country" id="country" required/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="contact_no">Contact Number :</label>
                    <input type="number" name="phn_number" id="contact_no" required/>
                </div>
                <div class="form-group">
                    <label for="email">Email ID :</label>
                    <input type="email" name="email" id="email" required/>
                </div>
                <div class="form-submit">
                    <button type="submit" class="btn btn-success">Add Customer</button>
                </div>
            </div>
        </form>
    </div>
</div>


<script>
  var loadFile = function(event) {
    var reader = new FileReader();
    reader.onload = function(){
      var output = document.getElementById('uploadImage');
      output.src = reader.result;
    };
    reader.readAsDataURL(event.target.files[0]);
  };
</script>


</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/room_management/book_room.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="{% static 'book_room/css/styles.css' %}" rel="stylesheet">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

    <title>Book Room</title>
</head>
<body style="background-color: #232525;">
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <nav class="colorlib-nav">
                <div class="top-menu">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-2 text-center">
                                <div id="colorlib-logo"><a href="{% url 'room_management:home' %}">BOOK HOTEL</a></div>
                            </div>
                            <div class="col-md-10 text-right">
                                <ul>
                                    <li class="active"><a href="{% url 'room_management:home' %}">Home</a></li>
                                    <li class="btn-cta"><a href="{% url 'room_management:logout' %}">Logout</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>



<div class="container form">
    <form method="POST">
        {% csrf_token %}
        <h1>Room Booking</h1>
        <div class="form-group">
            <label for="room">Available Rooms:</label>
            <select multiple class="form-control" id="room" name="room" required>
                {% for room in empty_rooms %}
                    <option>{{ room }}</option>
                    <hr>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="customer">Customer Aadhaar:</label>
            <select multiple class="form-control" id="customer" name="aadhaar" required>
                {% for customer in customers %}
                    <option>{{ customer.customer_aadhaar }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="days">No of days:</label>
            <input type="number" class="form-control" id="days" name="days" required>
        </div>
        <button type="submit" class="btn btn-outline-info">Book</button>
        <h4>Customer not Registered? <a href="{% url 'room_management:add-customer' %}">Add customer</a></h4>

        <marquee>This session will expire within 4 minutes.</marquee>
    </form>
</div>

</div>
</body>
</html>

templates/room_management/booked_rooms.html
<!DOCTYPE html>

{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Booked Rooms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'booked_rooms/css/style.css' %}">
</head>


<body>


<nav class="colorlib-nav">
    <div class="top-menu">
        <div class="col-md-2 text-center">
            <div id="colorlib-logo"><a href="{% url 'room_management:landing-page' %}">BOOK HOTEL</a></div>
        </div>
        <div class="col-md-10 text-right">
            <ul>
                <li class="active"><a href="{% url 'room_management:landing-page' %}">Home</a></li>
                <li class="btn-cta"><a href="{% url 'room_management:logout' %}">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>


<div class="container details">
    <div class="card" style="background-color: #282828; text-align: center" >
    <h3 style="text-align: center;color:#c1e2b3;margin-bottom: 50px;margin-top: 50px;">BOOKED ROOMS</h3>

    {% for room in rooms %}
        <div class="row" style="margin-bottom: 2%">
            <div class="col-md-2">
                {{ room.booked_customer }}
            </div>
            <div class="col-md-2">
                {{ room.room_number }}
            </div>
            <div class="col-md-2">
                {{ room.room_type_price }}
            </div>
            <div class="col-md-2">
                {{ room.block_floor }}
            </div>
            <div class="col-md-4">
                {{ room.deadline }}
            </div>

        </div>
        {% endfor %}
    </div>
</div>
</body>

</html>

templates/room_management/profile.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker3.css" rel="stylesheet">

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

    <title>Profile - {{ customer_details.customer_name }}</title>

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'customer_profile/css/style.css' %}">
</head>
<body>

<nav class="colorlib-nav">
    <div class="top-menu">
        <div class="col-md-2 text-center">
            <div id="colorlib-logo"><a href="{% url 'room_management:landing-page' %}">BOOK HOTEL</a></div>
        </div>
        <div class="col-md-10 text-right">
            <ul>
                <li class="active"><a href="{% url 'room_management:customers-list' %}">Back</a></li>
                <li class="active"><a href="{% url 'room_management:landing-page' %}">Home</a></li>
                <li class="btn-cta"><a href="{% url 'room_management:logout' %}">Logout</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <form method="POST" class="register-form" id="register-form" enctype="multipart/form-data"
              action="{% url 'room_management:edit-details' customer_details.customer_aadhaar %}">
            {% csrf_token %}
            <div class="col-lg-6 profile-img">
                <input type="file" accept=".png, .jpg, .jpeg" id="imageUpload" name="image" onchange="loadFile(event)">
                <label for="imageUpload">
                    <img
                        {% if customer_details.customer_image.url != None %}
                            src="{{ MEDIA_URL }}{{ customer_details.customer_image.url }}"
                        {% endif %}
                            src="{% static 'add_customer/images/add-image.png' %}"
                            alt="" style="height: 500px" id="uploadImage"
                         title="Upload Profile Image">
                </label>
                {% if customer_details.customer_image.url != None %}
                    <img src="{{ MEDIA_URL }}{{ customer_details.customer_image.url }}" alt="" style="height: 500px;" id="profileImage">
                {% else %}
                    <h3>No Image</h3>
                {% endif %}
            </div>

            <div class="col-lg-6" id="details">
                <h3>CUSTOMER DETAILS:</h3>
                <div class="form-row">
                    <div class="form-group">
                        <label for="name">Full Name :</label>
                        <h2 id="name">{{ customer_details.customer_name }}</h2>
                        <input type="text" name="cust_name" id="name-input"
                               value="{{ customer_details.customer_name }}" required/>
                    </div>
                    <div class="form-group">
                        <label for="aadhaar">Aadhaar No :</label>
                        <h2 id="aadhaar">{{ customer_details.customer_aadhaar }}</h2>
                        <input type="text" name="aadhaar" id="aadhaar-input"
                               value="{{ customer_details.customer_aadhaar }}" disabled
                        />
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="birth_date">DOB :</label>
                        <h2 id="birth_date">{{ customer_details.customer_dob }}</h2>
                        <input type="text" name="cust_dob" pattern="[0-9]{4}-[0-9]{1-2}-[0-9]{1-2}" id="birth_date-input"
                               placeholder="YYYY-MM-DD"
                               value="{{ customer_details.customer_dob.year }}-{{ customer_details.customer_dob.month }}-{{ customer_details.customer_dob.day }}"
                               disabled>
                    </div>
                    <div class="form-group">
                        <label for="gender">Gender: </label>
                        <h2 id="gender">{{ customer_details.gender }}</h2>
                        <input name="gender" id="gender-input"
                               value="{{ customer_details.gender }}" disabled>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="city">City :</label>
                        <h2 id="city">{{ customer_details.address.city }}</h2>
                        <input type="text" name="city" id="city-input"
                               value="{{ customer_details.address.city }}" disabled/>
                    </div>
                    <div class="form-group">
                        <label for="house_no">House No:</label>
                        <h2 id="house_no">{{ customer_details.address.house_number }}</h2>
                        <input type="text" name="house_number" id="house_number-input"
                               value="{{ customer_details.address.house_number }}" disabled/>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group">
                        <label for="state">State :</label>
                        <h2 id="state">{{ customer_details.address.state }}</h2>
                        <input type="text" name="state" id="state-input"
                               value="{{ customer_details.address.state }}" disabled/>
                    </div>
                    <div class="form-group">
                        <label for="country">Country:</label>
                        <h2 id="country">{{ customer_details.address.country }}</h2>
                        <input type="text" name="country" id="country-input"
                               value="{{ customer_details.address.country }}" disabled/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="contact_no">Contact Number :</label>
                    <h2 id="contact_no">{{ customer_details.contact_details.phone_number }}</h2>
                    <input type="text" name="phn_number" id="contact_no-input"
                           value="{{ customer_details.contact_details.phone_number }}" required/>
                </div>
                <div class="form-group">
                    <label for="email">Email ID :</label>
                    <h2 id="email">{{ customer_details.contact_details.email }}</h2>
                    <input type="email" name="email" id="email-input"
                           value="{{ customer_details.contact_details.email }}" required/>
                </div>
                <div class="form-submit">
                    <div class="btn-group" role="group" aria-label="Basic example" id="edit">
                        <a type="button" class="btn btn-success" name="edit" onclick="edit_mode_on()">
                            Edit Customer Details
                        </a>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal" style="text-transform: capitalize">
                            Delete Customer
                        </button>
                    </div>
                    <div class="btn-group" role="group" aria-label="Basic example" id="save">
                        <button type="submit" class="btn btn-success">Save Changes</button>
                        <a href="{% url 'room_management:customer-profile' customer_details.customer_aadhaar %}"
                           class="btn btn-warning">Cancel</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Delete Customer</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                Do you really want to delete the customer?
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                <a type="button" class="btn btn-danger"
                   href="{% url 'room_management:delete-customer' customer_details.customer_aadhaar %}">Delete</a>
            </div>

        </div>
    </div>
</div>


<script src="{% static 'customer_profile/js/jscript.js' %}"></script>

<script>
    var loadFile = function(event) {
        var reader = new FileReader();
        reader.onload = function(){
            var output = document.getElementById('uploadImage');
            output.src = document.querySelector('input[type=file]').files[0];
        };
        reader.readAsDataURL(event.target.files[0]);
    };
</script>


</body>
</html>